// apps/web/src/lib/components/app-sidebar.svelte
<script lang="ts">
	import {
		InboxIcon,
		Calendar1Icon,
		CalendarDaysIcon,
		HashIcon,
		ChartBarIcon,
		LogOutIcon,
		SettingsIcon,
		ChevronsUpDownIcon,
		SparklesIcon,
		BadgeCheckIcon,
		CreditCardIcon,
		BellIcon,
	} from '@lucide/svelte/icons'
	import Logo from '/static/logo.svg'
	import * as Sidebar from '$lib/components/ui/sidebar/index.js'
	import * as DropdownMenu from '$lib/components/ui/dropdown-menu/index.js'
	import type { ComponentProps } from 'svelte'
	import * as Avatar from '$lib/components/ui/avatar/index.js'

	// Menu items.
	const items = [
		{
			title: 'Overview',
			url: '/app/dashboard',
			icon: ChartBarIcon,
		},
		{
			title: 'Inbox',
			url: '/app/inbox',
			icon: InboxIcon,
		},
		{
			title: 'Upcoming',
			url: '/app/upcoming',
			icon: CalendarDaysIcon,
		},
	]
	
	
	let user: {
		name: string;
		email: string;
		avatar: string;
	} = {
		name: 'John Doe',
		email: 'john.doe@example.com',
		avatar: 'https://github.com/shadcn.png',
	}

	let { ref = $bindable(null), ...restProps }: ComponentProps<typeof Sidebar.Root> = $props()
	const sidebar = Sidebar.useSidebar();
</script>

<Sidebar.Root {...restProps} bind:ref>
	<Sidebar.Header>
		<Sidebar.Menu>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton size="lg">
					{#snippet child({ props })}
						<a href="##" {...props}>
							<div
								class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg"
							>
								<img src={Logo} alt="tue logo" />
							</div>
							<div class="grid flex-1 text-left text-sm leading-tight">
								<span class="truncate font-medium">Tue</span>
								<span class="truncate text-xs">task manager</span>
							</div>
						</a>
					{/snippet}
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
		</Sidebar.Menu>
	</Sidebar.Header>

	<Sidebar.Content>
		<Sidebar.Group>
			<Sidebar.Menu>
				{#each items as item (item.title)}
					<Sidebar.MenuItem>
						<Sidebar.MenuButton>
							{#snippet child({ props })}
								<a href={item.url} {...props}>
									<item.icon />
									<span>{item.title}</span>
								</a>
							{/snippet}
						</Sidebar.MenuButton>
					</Sidebar.MenuItem>
				{/each}
			</Sidebar.Menu>
		</Sidebar.Group>

		<Sidebar.Group>
			<Sidebar.GroupLabel>Projects</Sidebar.GroupLabel>
			<Sidebar.GroupContent>
				<Sidebar.Menu>
					{#each items as item (item.title)}
						<Sidebar.MenuItem>
							<Sidebar.MenuButton>
								{#snippet child({ props })}
									<a href={item.url} {...props}>
										<HashIcon />
										<span>{item.title}</span>
									</a>
								{/snippet}
							</Sidebar.MenuButton>
						</Sidebar.MenuItem>
					{/each}
				</Sidebar.Menu>
			</Sidebar.GroupContent>
		</Sidebar.Group>
	</Sidebar.Content>

	<Sidebar.Footer>
		<Sidebar.Menu>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton>
					{#snippet child({ props })}
						<a href="/app/settings" {...props}>
							<SettingsIcon />
							<span>Settings</span>
						</a>
					{/snippet}
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
			
			<!-- <Sidebar.MenuItem>
				<DropdownMenu.Root>
				  <DropdownMenu.Trigger>
					{#snippet child({ props })}
					  <Sidebar.MenuButton size="lg"
						class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
						{...props}>
						<Avatar.Root class="size-8 rounded-lg">
						  <Avatar.Image src={user.avatar} alt={user.name} />
						  <Avatar.Fallback class="rounded-lg">CN</Avatar.Fallback>
						</Avatar.Root>
						<div class="grid flex-1 text-left text-sm leading-tight">
						  <span class="truncate font-medium">{user.name}</span>
						  <span class="truncate text-xs">{user.email}</span>
						</div>
						<ChevronsUpDownIcon class="ml-auto size-4" />
					  </Sidebar.MenuButton>
					{/snippet}
				  </DropdownMenu.Trigger>
				  <DropdownMenu.Content
					class="w-(--bits-dropdown-menu-anchor-width) min-w-56 rounded-lg"
					side={sidebar.isMobile ? "bottom" : "right"}
					align="end"
					sideOffset={4}>
					<DropdownMenu.Label class="p-0 font-normal">
					  <div class="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
						<Avatar.Root class="size-8 rounded-lg">
						  <Avatar.Image src={user.avatar} alt={user.name} />
						  <Avatar.Fallback class="rounded-lg">CN</Avatar.Fallback>
						</Avatar.Root>
						<div class="grid flex-1 text-left text-sm leading-tight">
						  <span class="truncate font-medium">{user.name}</span>
						  <span class="truncate text-xs">{user.email}</span>
						</div>
					  </div>
					</DropdownMenu.Label>
					<DropdownMenu.Separator />
					<DropdownMenu.Group>
					  <DropdownMenu.Item>
						<SparklesIcon />
						Upgrade to Pro
					  </DropdownMenu.Item>
					</DropdownMenu.Group>
					<DropdownMenu.Separator />
					<DropdownMenu.Group>
					  <DropdownMenu.Item>
						<BadgeCheckIcon />
						Account
					  </DropdownMenu.Item>
					  <DropdownMenu.Item>
						<CreditCardIcon />
						Billing
					  </DropdownMenu.Item>
					  <DropdownMenu.Item>
						<BellIcon />
						Notifications
					  </DropdownMenu.Item>
					</DropdownMenu.Group>
					<DropdownMenu.Separator />
					<DropdownMenu.Item>
					  <LogOutIcon />
					  Log out
					</DropdownMenu.Item>
				  </DropdownMenu.Content>
				</DropdownMenu.Root>
			  </Sidebar.MenuItem> -->
		</Sidebar.Menu>
	</Sidebar.Footer>
</Sidebar.Root>

// apps/console/src/components/AppSidebar.vue
<script setup lang="ts">
import { type SidebarProps, useSidebar } from '@/components/ui/sidebar'
import {
  Command,
  Home,
  Inbox,
  Search,
  Sparkles,
  StarOff,
  Link,
  ArrowUpRight,
  Trash2,
  MoreHorizontal
} from 'lucide-vue-next'
import {
	Sidebar,
	SidebarContent,
	SidebarFooter,
	SidebarHeader,
	SidebarMenu,
	SidebarMenuButton,
	SidebarMenuItem,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarMenuAction,
} from '@/components/ui/sidebar'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"

const props = withDefaults(defineProps<SidebarProps>(), {})

const { isMobile } = useSidebar()
const data = {

  navMain: [
    {
      title: "Search",
      url: "#",
      icon: Search,
    },
    {
      title: "Ask AI",
      url: "#",
      icon: Sparkles,
    },
    {
      title: "Home",
      url: "#",
      icon: Home,
      isActive: true,
    },
    {
      title: "Inbox",
      url: "#",
      icon: Inbox,
      badge: "10",
    },
  ],
  favorites: [
    {
      name: "Jood",
      url: "#",
      emoji: "📊",
    },
    {
      name: "Jlox",
      url: "#",
      emoji: "🍳",
    },
    {
      name: "Introduction into Algorithm",
      url: "#",
      emoji: "💪",
    },
  ],
}
</script>

<template>
	<Sidebar v-bind="props">
		<SidebarHeader>
			<SidebarMenu>
				<SidebarMenuItem>
					<SidebarMenuButton size="lg" as-child>
						<a href="#">
							<div class="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
								<Command class="size-4" />
							</div>
							<div class="grid flex-1 text-left text-sm leading-tight">
								<span class="truncate font-medium">
                  Acme Inc
                </span>
								<span class="truncate text-xs">Enterprise</span>
							</div>
						</a>
					</SidebarMenuButton>
				</SidebarMenuItem>
			</SidebarMenu>

      <SidebarMenu>
        <SidebarMenuItem v-for="item in data.navMain" :key="item.title">
          <SidebarMenuButton as-child :is-active="item.isActive">
            <a :href="item.url">
              <component :is="item.icon" />
              <span>{{ item.title }}</span>
            </a>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </SidebarMenu>
		</SidebarHeader>
		<SidebarContent>

      <SidebarGroup class="group-data-[collapsible=icon]:hidden">
        <SidebarGroupLabel>Projects</SidebarGroupLabel>
        <SidebarMenu>
          <SidebarMenuItem v-for="item in data.favorites" :key="item.name">
            <SidebarMenuButton as-child>
              <a :href="item.url" :title="item.name">
                <span>{{ item.emoji }}</span>
                <span>{{ item.name }}</span>
              </a>
            </SidebarMenuButton>
            <DropdownMenu>
              <DropdownMenuTrigger as-child>
                <SidebarMenuAction show-on-hover>
                  <MoreHorizontal />
                  <span class="sr-only">More</span>
                </SidebarMenuAction>
              </DropdownMenuTrigger>
              <DropdownMenuContent
                class="w-56 rounded-lg"
                :side="isMobile ? 'bottom' : 'right'"
                :align="isMobile ? 'end' : 'start'"
              >
                <DropdownMenuItem>
                  <StarOff class="text-muted-foreground" />
                  <span>Remove from Favorites</span>
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <Link class="text-muted-foreground" />
                  <span>Copy Link</span>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <ArrowUpRight class="text-muted-foreground" />
                  <span>Open in New Tab</span>
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <Trash2 class="text-muted-foreground" />
                  <span>Delete</span>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </SidebarMenuItem>

          <SidebarMenuItem>
            <SidebarMenuButton class="text-sidebar-foreground/70">
              <MoreHorizontal />
              <span>More</span>
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarGroup>
		</SidebarContent>
		<SidebarFooter>
		</SidebarFooter>
	</Sidebar>
</template>
